- name: Install required dnf packages({{DNF_PKGS}})
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop: "{{DNF_PKGS}}"

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started

- name: Create folder, Download and Extract code files (import tasks form common role)
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: download_extract.yml

- name: Copy config file
  tags:
  - configuration
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart nginx
