- name: Install required dnf packages({{DNF_PKGS}})
  ansible.builtin.dnf:
    name: "{{DNF_PKGS}}"
    state: present

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started

- name: Remove previous code files at {{CODE_DIR}}
  ansible.builtin.file:
    path: "{{CODE_DIR}}/"
    state: absent

- name: Create folder, Download and extract code files (import tasks form common role)
  ansible.builtin.import_role:
    name: common
    tasks_form: download_extract.yml

- name: Copy config file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
