- name: Install required dnf packages({{DNF_PKGS}})
  ansible.builtin.dnf:
    name: "{{DNF_PKGS}}"
    state: present
  notify: Start nginx

- name: Remove previous code files at {{CODE_DIR}}
  ansible.builtin.file:
    path: "{{CODE_DIR}}/"
    state: absent

- name: Create folder, Download and extract code files (import tasks form common role)
  ansible.builtin.import_role:
    name: common
    tasks_from: download_extract.yml

- name: Copy config file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
