- name: Install required pip packages({{PIP_PKGS}})
  ansible.builtin.pip:
    name: "{{PIP_PKGS}}"

- name: Installing required dnf packages({{DNF_PKGS}})
  ansible.builtin.dnf:
    name: "{{DNF_PKGS}}"
    state: present
  notify: Start and enable mysql server

- name: Start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Check if root password of mysql is set
  community.mysql.mysql_info:
    login_host: "{{MYSQL_DNS}}"
    login_user: "{{MYSQL_USER}}"
    login_password: "{{MYSQL_PASS}}"
  register: mysql_info
  ignore_errors: true

- name: print mysql_info var output
  ansible.builtin.debug:
    msg: "{{mysql_info}}"

- name: If root password not set, then set it
  ansible.builtin.command: "{{CMD_MYSQL_SET_PASS}}"
  when: mysql_info.failed is true
