COMPONENT: backend
PIP_PKGS:
- PyMySQL
- cryptography
DNF_PKGS:
- nodejs
- mysql
APP_USER: expense
CODE_DIR: /app
SCHEMA_FILE: "{{CODE_DIR}}/schema/backend.sql"
CMD_TO_ENABLE_NODEJS20: sudo dnf module disable nodejs -y; sudo dnf module enable nodejs:20 -y
