- name: Delete old code
  ansible.builtin.file:
    path: "{{CODE_DIR}}"
    state: absent
  ignore_errors: true

- name: Create directory {{CODE_DIR}} for new code files
  ansible.builtin.file:
    path: "{{CODE_DIR}}"
    state: directory

- name: Download and Extract code files to {{CODE_DIR}}
  ansible.builtin.unarchive:
    src: "{{CODE_URL}}"
    dest: "{{CODE_DIR}}"
    remote_src: true
